In [1]:
import numpy as np
print(np.__version__)

2.4.2


- 데이터 분석 : 수치형 변수의 요약, 통게, 시각화
- 이미지처리: 이미지데이터
- 게임/시뮬레이션 : 시뮬레이션 구현
- 머신러닝/딥러닝: 금융, 의료, 실험, 센서 데이터

In [44]:
# 기본적 배열(ndarray) 생성
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))  # [1 2 3 4 5]
arr.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

# 넘파이 배열의 속성 ndarray

In [45]:
# 넘파이의 집계 함수
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [47]:
# 배열의 형태 보기(shape), 차원의 개수(ndim)
np.array([7]).shape, np.array([7]).ndim
#1차원, 열1개

((1,), 1)

In [11]:
np.array([7,2]).shape, np.array([7,2]).ndim

((2,), 1)

In [12]:
np.array([[10,10]]).shape, np.array([[10,10]]).ndim 

((1, 2), 2)

In [13]:
np.array([[10,10], [15,15]]).shape, np.array([[10,10], [15,15]]).ndim

((2, 2), 2)

In [14]:
np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]]).shape, np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]]).ndim

((2, 2, 3), 3)

In [17]:
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

arr1.shape, arr12.shape

((5,), (2, 5))

In [29]:
# (3,5) 행렬 arr13 만들기

arr13 = np.arange(1,16).reshape(3,5)
arr13.shape
arr13.dtype

dtype('int64')

In [30]:
# 0으로 채워진 배열 생성
arr2 = np.zeros(5)
arr2.shape
arr2.dtype

dtype('float64')

In [31]:
# 1로 채워진 배열 생성
arr3 = np.ones((3, 3))
arr3.shape
arr3.dtype

dtype('float64')

In [25]:
# 1부터 10까지 2씩 증가하는 배열
range_arr = np.arange(1, 10, 2)  
print(range_arr)

[1 3 5 7 9]


In [26]:
 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)

[  0.  25.  50.  75. 100.]


In [27]:
# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
print(random_arr)

[[0.2069774  0.64666365 0.86900749]
 [0.15615673 0.93172498 0.9707642 ]]


# array의 데이터 타입 변환

In [32]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [33]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생

ValueError: invalid literal for int() with base 10: np.str_('three')

In [36]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [38]:
data = [
    [120, 150, 180],
    [100, 130, 160],
    [90, 110, 140]]

type(data)

list

In [39]:
# 생산량 합계 확인
total_production = [sum(product) for product in data]
total_production

[450, 390, 340]

In [40]:
prod_data = np.array(data)
prod_data.shape

(3, 3)

In [41]:
np.sum(prod_data, axis=1)

array([450, 390, 340])

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [ ]:
# 생산량 * 단가(이익율) = 총매출(총이익)

profit_per_unit = np.array([20,30,25])

# 배열 인덱싱

In [ ]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])

1
5


In [49]:
# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3], [4,5,6]])
print(arr_2d[0,1])
print(arr_2d[1,-1])

2
6


In [50]:
# 1차원 배열 슬라이싱
arr = np.array([0,1,2,3,4,5])
print(arr[2:5])  # [2 3 4]
print(arr[::2])  # [0 2 4]

[2 3 4]
[0 2 4]


In [51]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print(arr_2d[:2, 1:3])

[[2 3]
 [6 7]]


In [52]:
# 3차원 Array 만들기

arr = np.arange(108).reshape(3, 6, 6)
print(arr)
print("shape:", arr.shape)

[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]
  [ 24  25  26  27  28  29]
  [ 30  31  32  33  34  35]]

 [[ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]
  [ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]
  [ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]]

 [[ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]
  [ 84  85  86  87  88  89]
  [ 90  91  92  93  94  95]
  [ 96  97  98  99 100 101]
  [102 103 104 105 106 107]]]
shape: (3, 6, 6)


In [59]:
arr_3d = np.tile(np.arange(36).reshape(6,6), (4,1,1))
arr_3d.shape

(4, 6, 6)

In [60]:
arr_3d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [56]:
# 3차원 배열 슬라이싱
print(arr_3d[0, :3, :3])

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [ ]:
# 불린 인덱싱 예제 - '필터'할 때 많이 사용함
arr = np.array([1, 2, 3, 4, 5])
bool_array = np.array([True, False, True, False, True])
print("불린 인덱싱:", arr[bool_array])  # [1 3 5]

불린 인덱싱: [1 3 5]


In [62]:
# 마스킹 예제
mask = arr > 3  # 조건식으로 마스크 생성
arr[mask] = 0   # 마스크를 사용한 값 수정
print("마스킹 결과:", arr)  # [1 2 3 0 0]

마스킹 결과: [1 2 3 0 0]


In [63]:
# 팬시 인덱싱
indices = np.array([0, 2, 4]) # 정수배열로 인덱싱
print(arr[indices])    # [1 3 5]

[1 3 0]
